# -*- coding: utf-8 -*-
"""with_item_features3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rdo_UNWDECtpHBsAmG-CLxPAJ1-JU_Ly
"""

import numpy as np
raw_data = dict()
raw_data['max_user'] = 19243
raw_data['max_item'] = 165906

raw_data['train_data'] = np.load('tradesy/user_data_train.npy')

raw_data['val_data'] = np.load('tradesy/user_data_val.npy')
raw_data['test_data'] = np.load('tradesy/user_data_test.npy')

raw_data['item_features'] = np.load('tradesy/item_features.npy') / 32.671101



import os
import sys
sys.path.append(os.getcwd())

from openrec import ImplicitModelTrainer
from openrec.utils import ImplicitDataset
from openrec.recommenders import CML
from openrec.utils.evaluators import AUC, Recall
from openrec.utils.samplers import PairwiseSampler

#@title Default title text

batch_size = 1000
test_batch_size = 100
item_serving_size = 1000
display_itr = 10000

train_dataset = ImplicitDataset(raw_data['train_data'], raw_data['max_user'], raw_data['max_item'], name='Train')
val_dataset = ImplicitDataset(raw_data['val_data'], raw_data['max_user'], raw_data['max_item'], name='Val')
test_dataset = ImplicitDataset(raw_data['test_data'], raw_data['max_user'], raw_data['max_item'], name='Test')

cml_model = CML(batch_size=batch_size, max_user=train_dataset.max_user(), max_item=train_dataset.max_item(), 
                dim_embed=20, opt='Adam')
sampler = PairwiseSampler(batch_size=batch_size, dataset=train_dataset, num_process=5)
model_trainer = ImplicitModelTrainer(batch_size=batch_size, test_batch_size=test_batch_size, 
    train_dataset=train_dataset, model=cml_model, sampler=sampler)
auc_evaluator = AUC()

model_trainer.train(num_itr=int(1e5), display_itr=display_itr, eval_datasets=[val_dataset, test_dataset],
                    evaluators=[auc_evaluator])
